# Generated by Django 4.1.2 on 2022-10-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='replies',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bboard.reply', verbose_name='Reply'),
        ),
    ]
