# Generated by Django 4.1.2 on 2022-10-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_post_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bboard.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='replies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bboard.reply', verbose_name='Reply'),
        ),
    ]
